# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.models.resource_update_post_request import ResourceUpdatePostRequest

class TestResourceUpdatePostRequest(unittest.TestCase):
    """ResourceUpdatePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceUpdatePostRequest:
        """Test ResourceUpdatePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceUpdatePostRequest`
        """
        model = ResourceUpdatePostRequest()
        if include_optional:
            return ResourceUpdatePostRequest(
                key = 'assets/ships/0001/full.webp',
                timestamp = 1740262942000
            )
        else:
            return ResourceUpdatePostRequest(
                key = 'assets/ships/0001/full.webp',
                timestamp = 1740262942000,
        )
        """

    def testResourceUpdatePostRequest(self):
        """Test ResourceUpdatePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
