# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.models.api_data_post200_response import ApiDataPost200Response

class TestApiDataPost200Response(unittest.TestCase):
    """ApiDataPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDataPost200Response:
        """Test ApiDataPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDataPost200Response`
        """
        model = ApiDataPost200Response()
        if include_optional:
            return ApiDataPost200Response(
                result = 'OK'
            )
        else:
            return ApiDataPost200Response(
                result = 'OK',
        )
        """

    def testApiDataPost200Response(self):
        """Test ApiDataPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
