# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.models.api_data_post_request import ApiDataPostRequest

class TestApiDataPostRequest(unittest.TestCase):
    """ApiDataPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDataPostRequest:
        """Test ApiDataPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDataPostRequest`
        """
        model = ApiDataPostRequest()
        if include_optional:
            return ApiDataPostRequest(
                member_id = 123456789,
                request = x_ray_webhook.models._api_data_post_request_request._api_data_post_request_request(
                    url = 'https://w01y.kancolle-server.com/kcsapi/api_get_member/basic', 
                    parameters = {"key1":"value1","key2":"value2"}, ),
                response = x_ray_webhook.models._api_data_post_request_response._api_data_post_request_response(
                    timestamp = 1740262942000, 
                    data = {"member_id":"123456789","nickname":"Admiral 56"}, ),
                log = x_ray_webhook.models._api_data_post_request_log._api_data_post_request_log(
                    bucket = 'x-ray-log', 
                    key = 'sortie_log/2025/02/22/222222_222222_kcsapi_api_req_sortie_battle.json.br', )
            )
        else:
            return ApiDataPostRequest(
                member_id = 123456789,
                request = x_ray_webhook.models._api_data_post_request_request._api_data_post_request_request(
                    url = 'https://w01y.kancolle-server.com/kcsapi/api_get_member/basic', 
                    parameters = {"key1":"value1","key2":"value2"}, ),
                response = x_ray_webhook.models._api_data_post_request_response._api_data_post_request_response(
                    timestamp = 1740262942000, 
                    data = {"member_id":"123456789","nickname":"Admiral 56"}, ),
        )
        """

    def testApiDataPostRequest(self):
        """Test ApiDataPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
