# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.models.api_data_post_request_request import ApiDataPostRequestRequest

class TestApiDataPostRequestRequest(unittest.TestCase):
    """ApiDataPostRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDataPostRequestRequest:
        """Test ApiDataPostRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDataPostRequestRequest`
        """
        model = ApiDataPostRequestRequest()
        if include_optional:
            return ApiDataPostRequestRequest(
                url = 'https://w01y.kancolle-server.com/kcsapi/api_get_member/basic',
                parameters = {"key1":"value1","key2":"value2"}
            )
        else:
            return ApiDataPostRequestRequest(
                url = 'https://w01y.kancolle-server.com/kcsapi/api_get_member/basic',
                parameters = {"key1":"value1","key2":"value2"},
        )
        """

    def testApiDataPostRequestRequest(self):
        """Test ApiDataPostRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
