# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.models.api_data_post_request_response_data import ApiDataPostRequestResponseData

class TestApiDataPostRequestResponseData(unittest.TestCase):
    """ApiDataPostRequestResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDataPostRequestResponseData:
        """Test ApiDataPostRequestResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDataPostRequestResponseData`
        """
        model = ApiDataPostRequestResponseData()
        if include_optional:
            return ApiDataPostRequestResponseData(
            )
        else:
            return ApiDataPostRequestResponseData(
        )
        """

    def testApiDataPostRequestResponseData(self):
        """Test ApiDataPostRequestResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
