# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from x_ray_webhook.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_data_post(self) -> None:
        """Test case for api_data_post

        """
        pass

    async def test_member_info_post(self) -> None:
        """Test case for member_info_post

        """
        pass

    async def test_resource_update_post(self) -> None:
        """Test case for resource_update_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
