configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/private%2Fx-ray-webhook-27786bc3023e0f3f01f601c1c27387a98a6d6bfe96e3f99f2f19afc5ba09cc0b.yml
openapi_spec_hash: cc5d64f4afba6ce9ceb3fb4c730a33f4
config_hash: 4e37c562552f6a1ce64de981d9febcd3
