# coding: utf-8

"""
    X-Ray Webhook API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from x_ray_webhook.models.api_data_post_request_log import ApiDataPostRequestLog
from x_ray_webhook.models.api_data_post_request_request import ApiDataPostRequestRequest
from x_ray_webhook.models.api_data_post_request_response import ApiDataPostRequestResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApiDataPostRequest(BaseModel):
    """
    ApiDataPostRequest
    """ # noqa: E501
    member_id: Annotated[int, Field(strict=True, ge=0)] = Field(description="Member ID", json_schema_extra={"examples": [123456789]})
    request: ApiDataPostRequestRequest
    response: ApiDataPostRequestResponse
    log: Optional[ApiDataPostRequestLog] = None
    __properties: ClassVar[List[str]] = ["member_id", "request", "response", "log"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiDataPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request
        if self.request:
            _dict['request'] = self.request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response
        if self.response:
            _dict['response'] = self.response.to_dict()
        # override the default output from pydantic by calling `to_dict()` of log
        if self.log:
            _dict['log'] = self.log.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiDataPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "member_id": obj.get("member_id"),
            "request": ApiDataPostRequestRequest.from_dict(obj["request"]) if obj.get("request") is not None else None,
            "response": ApiDataPostRequestResponse.from_dict(obj["response"]) if obj.get("response") is not None else None,
            "log": ApiDataPostRequestLog.from_dict(obj["log"]) if obj.get("log") is not None else None
        })
        return _obj


