name: Release Doctor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_doctor:
    name: release doctor
    runs-on: depot-ubuntu-24.04
    if: github.repository == 'rsky/x-ray-webhook-python' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please') || github.head_ref == 'next')

    steps:
      - uses: actions/checkout@v4

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
        env:
          PYPI_TOKEN: ${{ secrets.X_RAY_WEBHOOK_PYPI_TOKEN || secrets.PYPI_TOKEN }}
